package io.github.diegobr4nd.lectorbilingue.core.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/** Paleta "Tinta y papel": azul tinta sobre crema (claro). Sin color dinámico. */
val TintaLight: ColorScheme = lightColorScheme(
    primary = Color(0xFF2E4A7D),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFDCE5F8),
    onPrimaryContainer = Color(0xFF0F2147),
    secondary = Color(0xFF55596A),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE7E2D4),
    onSecondaryContainer = Color(0xFF2B2A24),
    tertiary = Color(0xFF6B4A1F),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFF4ECD8),
    onTertiaryContainer = Color(0xFF3B2F1E),
    background = Color(0xFFFBF8F1),
    onBackground = Color(0xFF1C1B1F),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF1C1B1F),
    surfaceVariant = Color(0xFFEDE9DF),
    onSurfaceVariant = Color(0xFF4A473F),
    surfaceTint = Color(0xFF2E4A7D),
    inverseSurface = Color(0xFF312F33),
    inverseOnSurface = Color(0xFFF4EFF4),
    inversePrimary = Color(0xFFA9C1F0),
    outline = Color(0xFF8A8579),
    outlineVariant = Color(0xFFCFC9BB),
    error = Color(0xFFB3261E),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFF9DEDC),
    onErrorContainer = Color(0xFF410E0B),
    surfaceBright = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFE2DED4),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF7F3EA),
    surfaceContainer = Color(0xFFF2EEE4),
    surfaceContainerHigh = Color(0xFFECE8DE),
    surfaceContainerHighest = Color(0xFFE6E2D8),
)

/** Paleta "Tinta y papel" oscura: azul suave sobre grafito. */
val TintaDark: ColorScheme = darkColorScheme(
    primary = Color(0xFFA9C1F0),
    onPrimary = Color(0xFF0E2447),
    primaryContainer = Color(0xFF2E4A7D),
    onPrimaryContainer = Color(0xFFDCE5F8),
    secondary = Color(0xFFBFC6D6),
    onSecondary = Color(0xFF292F3C),
    secondaryContainer = Color(0xFF2F3542),
    onSecondaryContainer = Color(0xFFDDE3F0),
    tertiary = Color(0xFFE3C595),
    onTertiary = Color(0xFF3B2F1E),
    tertiaryContainer = Color(0xFF55401F),
    onTertiaryContainer = Color(0xFFF4ECD8),
    background = Color(0xFF121418),
    onBackground = Color(0xFFE6E3DD),
    surface = Color(0xFF1E222A),
    onSurface = Color(0xFFE6E3DD),
    surfaceVariant = Color(0xFF2A2F38),
    onSurfaceVariant = Color(0xFFC3C7D0),
    surfaceTint = Color(0xFFA9C1F0),
    inverseSurface = Color(0xFFE6E3DD),
    inverseOnSurface = Color(0xFF1C1B1F),
    inversePrimary = Color(0xFF2E4A7D),
    outline = Color(0xFF8D93A0),
    outlineVariant = Color(0xFF454B57),
    error = Color(0xFFF2B8B5),
    onError = Color(0xFF601410),
    errorContainer = Color(0xFF8C1D18),
    onErrorContainer = Color(0xFFF9DEDC),
    surfaceBright = Color(0xFF2E333D),
    surfaceDim = Color(0xFF121418),
    surfaceContainerLowest = Color(0xFF0D0F13),
    surfaceContainerLow = Color(0xFF181B21),
    surfaceContainer = Color(0xFF1E222A),
    surfaceContainerHigh = Color(0xFF282C35),
    surfaceContainerHighest = Color(0xFF333843),
)
